networks:
  expense: {}

volumes:
  mysql:

services:
  backend:
    image: sandeepgompa/backend:1.0.0
    command: sh -c "sleep 15 && node /opt/backend/index.js"
    networks:
      - expense
    container_name: backend
    depends_on:
      - mysql

  mysql:
    image: sandeepgompa/mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql  # ✅ Correct syntax

  frontend:
    image: sandeepgompa/frontend:1.0.0
    networks:
      - expense
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
